#include "Assembler.hpp"

#if defined(HAVE_KEYSTONE)
#include <keystone/keystone.h>

namespace {

struct ThreadKeystoneState {
    ks_engine *engine{nullptr};
    bool inUse{false};

    ~ThreadKeystoneState() {
        if (engine) {
            ks_close(engine);
            engine = nullptr;
        }
    }
};

static thread_local ThreadKeystoneState t_ks;

} // namespace
#endif

#include <QProcess>
#include <QTemporaryFile>
#include <QFile>
#include <QDir>
#include <sstream>

namespace edb_next {

Result<std::vector<uint8_t>> Assembler::assemble(const std::string& instruction, Address origin) {
    if (instruction.empty()) {
        return Result<std::vector<uint8_t>>::Err("Instruction cannot be empty");
    }

    std::string cleanInsn = instruction;
    // Remove trailing semicolons or whitespace
    while (!cleanInsn.empty() && (cleanInsn.back() == ';' || cleanInsn.back() == ' ' || cleanInsn.back() == '\t')) {
        cleanInsn.pop_back();
    }
    if (cleanInsn.empty()) {
        return Result<std::vector<uint8_t>>::Err("Instruction cannot be empty");
    }

#if defined(HAVE_KEYSTONE)
    // 1. Fast In-Memory Assembly via Keystone Engine (Microsecond response, zero disk I/O)
    ks_engine *ks = nullptr;
    bool standalone = false;

    if (!t_ks.inUse) {
        if (!t_ks.engine) {
            if (ks_open(KS_ARCH_X86, KS_MODE_64, &t_ks.engine) == KS_ERR_OK) {
                ks_option(t_ks.engine, KS_OPT_SYNTAX, KS_OPT_SYNTAX_INTEL);
            }
        }
        if (t_ks.engine) {
            ks = t_ks.engine;
            t_ks.inUse = true;
        }
    }

    if (!ks) {
        if (ks_open(KS_ARCH_X86, KS_MODE_64, &ks) == KS_ERR_OK) {
            ks_option(ks, KS_OPT_SYNTAX, KS_OPT_SYNTAX_INTEL);
            standalone = true;
        }
    }

    if (ks) {
        unsigned char *encode = nullptr;
        size_t size = 0;
        size_t count = 0;

        int ret = ks_asm(ks, cleanInsn.c_str(), origin.value(), &encode, &size, &count);
        if (ret == 0 && size > 0 && encode != nullptr) {
            std::vector<uint8_t> result(encode, encode + size);
            ks_free(encode);
            if (standalone) {
                ks_close(ks);
            } else {
                t_ks.inUse = false;
            }
            return Result<std::vector<uint8_t>>::Ok(std::move(result));
        }

        std::string errMsg = ks_strerror(ks_errno(ks));
        if (encode) ks_free(encode);
        if (standalone) {
            ks_close(ks);
        } else {
            t_ks.inUse = false;
        }
        return Result<std::vector<uint8_t>>::Err("Assembler error: " + errMsg);
    }
#endif

    // 2. Fallback: System GNU as + ld + objcopy via external process
    QTemporaryFile srcFile(QDir::tempPath() + "/edb_asm_XXXXXX.s");
    srcFile.setAutoRemove(true);
    if (!srcFile.open()) {
        return Result<std::vector<uint8_t>>::Err("Failed to create temporary assembly file");
    }

    std::ostringstream asmContent;
    asmContent << ".intel_syntax noprefix\n";
    asmContent << ".code64\n";
    asmContent << ".text\n";
    asmContent << cleanInsn << "\n";

    srcFile.write(asmContent.str().c_str());
    srcFile.flush();
    QString srcPath = srcFile.fileName();

    QString objPath = srcPath + ".o";
    QString binPath = srcPath + ".bin";

    // 2.1 Run 'as'
    QProcess asProc;
    QStringList asArgs;
    asArgs << "-o" << objPath << srcPath;
    asProc.start("as", asArgs);
    if (!asProc.waitForFinished(3000) || asProc.exitCode() != 0) {
        QString err = asProc.readAllStandardError();
        if (err.isEmpty()) err = asProc.readAllStandardOutput();
        QFile::remove(objPath);
        return Result<std::vector<uint8_t>>::Err("Assembler error: " + err.trimmed().toStdString());
    }

    // 2.2 Extract machine bytes
    // If origin is non-zero, use 'ld -Ttext <origin>' to resolve relative branch relocations (e.g. jmp/call)
    bool extracted = false;
    if (!origin.isNull()) {
        QProcess ldProc;
        QStringList ldArgs;
        ldArgs << "-m" << "elf_x86_64" << "-Ttext" << QString::fromStdString(origin.toHex())
               << "-o" << binPath << objPath << "--oformat" << "binary";
        ldProc.start("ld", ldArgs);
        if (ldProc.waitForFinished(3000) && ldProc.exitCode() == 0) {
            extracted = true;
        }
    }

    if (!extracted) {
        // Fallback or default extraction via objcopy
        QProcess objcopyProc;
        QStringList objcopyArgs;
        objcopyArgs << "-O" << "binary" << "-j" << ".text" << objPath << binPath;
        objcopyProc.start("objcopy", objcopyArgs);
        if (!objcopyProc.waitForFinished(3000) || objcopyProc.exitCode() != 0) {
            QString err = objcopyProc.readAllStandardError();
            QFile::remove(objPath);
            QFile::remove(binPath);
            return Result<std::vector<uint8_t>>::Err("objcopy error: " + err.trimmed().toStdString());
        }
    }

    // 2.3 Read generated bytes
    QFile binFile(binPath);
    if (!binFile.open(QIODevice::ReadOnly)) {
        QFile::remove(objPath);
        QFile::remove(binPath);
        return Result<std::vector<uint8_t>>::Err("Failed to read assembled binary output");
    }

    QByteArray bytes = binFile.readAll();
    binFile.close();

    // Clean up
    QFile::remove(objPath);
    QFile::remove(binPath);

    if (bytes.isEmpty()) {
        return Result<std::vector<uint8_t>>::Err("Assembly produced 0 bytes of code");
    }

    std::vector<uint8_t> result(bytes.begin(), bytes.end());
    return Result<std::vector<uint8_t>>::Ok(std::move(result));
}

} // namespace edb_next
