#include "Assembler.hpp"
#include <QProcess>
#include <QTemporaryFile>
#include <QFile>
#include <QDir>
#include <sstream>

namespace edb_next {

Result<std::vector<uint8_t>> Assembler::assemble(const std::string& instruction, Address origin) {
    if (instruction.empty()) {
        return Result<std::vector<uint8_t>>::Err("Instruction cannot be empty");
    }

    QTemporaryFile srcFile(QDir::tempPath() + "/edb_asm_XXXXXX.s");
    srcFile.setAutoRemove(true);
    if (!srcFile.open()) {
        return Result<std::vector<uint8_t>>::Err("Failed to create temporary assembly file");
    }

    std::string cleanInsn = instruction;
    // Remove trailing semicolons or whitespace
    while (!cleanInsn.empty() && (cleanInsn.back() == ';' || cleanInsn.back() == ' ' || cleanInsn.back() == '\t')) {
        cleanInsn.pop_back();
    }

    std::ostringstream asmContent;
    asmContent << ".intel_syntax noprefix\n";
    asmContent << ".code64\n";
    asmContent << ".text\n";
    asmContent << cleanInsn << "\n";

    srcFile.write(asmContent.str().c_str());
    srcFile.flush();
    QString srcPath = srcFile.fileName();

    QString objPath = srcPath + ".o";
    QString binPath = srcPath + ".bin";

    // 1. Run 'as'
    QProcess asProc;
    QStringList asArgs;
    asArgs << "-o" << objPath << srcPath;
    asProc.start("as", asArgs);
    if (!asProc.waitForFinished(3000) || asProc.exitCode() != 0) {
        QString err = asProc.readAllStandardError();
        if (err.isEmpty()) err = asProc.readAllStandardOutput();
        QFile::remove(objPath);
        return Result<std::vector<uint8_t>>::Err("Assembler error: " + err.trimmed().toStdString());
    }

    // 2. Extract machine bytes
    // If origin is non-zero, use 'ld -Ttext <origin>' to resolve relative branch relocations (e.g. jmp/call)
    bool extracted = false;
    if (!origin.isNull()) {
        QProcess ldProc;
        QStringList ldArgs;
        ldArgs << "-m" << "elf_x86_64" << "-Ttext" << QString::fromStdString(origin.toHex())
               << "-o" << binPath << objPath << "--oformat" << "binary";
        ldProc.start("ld", ldArgs);
        if (ldProc.waitForFinished(3000) && ldProc.exitCode() == 0) {
            extracted = true;
        }
    }

    if (!extracted) {
        // Fallback or default extraction via objcopy
        QProcess objcopyProc;
        QStringList objcopyArgs;
        objcopyArgs << "-O" << "binary" << "-j" << ".text" << objPath << binPath;
        objcopyProc.start("objcopy", objcopyArgs);
        if (!objcopyProc.waitForFinished(3000) || objcopyProc.exitCode() != 0) {
            QString err = objcopyProc.readAllStandardError();
            QFile::remove(objPath);
            QFile::remove(binPath);
            return Result<std::vector<uint8_t>>::Err("objcopy error: " + err.trimmed().toStdString());
        }
    }

    // 3. Read generated bytes
    QFile binFile(binPath);
    if (!binFile.open(QIODevice::ReadOnly)) {
        QFile::remove(objPath);
        QFile::remove(binPath);
        return Result<std::vector<uint8_t>>::Err("Failed to read assembled binary output");
    }

    QByteArray bytes = binFile.readAll();
    binFile.close();

    // Clean up
    QFile::remove(objPath);
    QFile::remove(binPath);

    if (bytes.isEmpty()) {
        return Result<std::vector<uint8_t>>::Err("Assembly produced 0 bytes of code");
    }

    std::vector<uint8_t> result(bytes.begin(), bytes.end());
    return Result<std::vector<uint8_t>>::Ok(std::move(result));
}

} // namespace edb_next
